'use strict';

/* ── DOM Cache ── */
/* ── DOM Cache ── */
const el = {
  particles: document.getElementById("particles"),
  coupleNames: document.getElementById("coupleNames"),
  weddingDateDisplay: document.getElementById("weddingDateDisplay"),
  countdown: document.getElementById("countdown"),
  statTotal: document.getElementById("statTotal"),
  statConfirmed: document.getElementById("statConfirmed"),
  statPending: document.getElementById("statPending"),
  statDeclined: document.getElementById("statDeclined"),
  statTables: document.getElementById("statTables"),
  statSeated: document.getElementById("statSeated"),
  statSent: document.getElementById("statSent"),
  statUnsent: document.getElementById("statUnsent"),
  statGroomSide: document.getElementById("statGroomSide"),
  statBrideSide: document.getElementById("statBrideSide"),
  statVeg: document.getElementById("statVeg"),
  statAccessibility: document.getElementById("statAccessibility"),
  progressFill: document.getElementById("progressFill"),
  progressPercent: document.getElementById("progressPercent"),
  guestCount: document.getElementById("guestCount"),
  guestTableBody: document.getElementById("guestTableBody"),
  guestsEmpty: document.getElementById("guestsEmpty"),
  guestSearch: document.getElementById("guestSearch"),
  seatingFloor: document.getElementById("seatingFloor"),
  tablesEmpty: document.getElementById("tablesEmpty"),
  unassignedGuests: document.getElementById("unassignedGuests"),
  invitationImage: document.getElementById("invitationImage"),
  waTemplate: document.getElementById("waTemplate"),
  waPreviewBubble: document.getElementById("waPreviewBubble"),
  waPreviewTime: document.getElementById("waPreviewTime"),
  waGuestList: document.getElementById("waGuestList"),
  toastContainer: document.getElementById("toastContainer"),
  guestModal: document.getElementById("guestModal"),
  tableModal: document.getElementById("tableModal"),
  topBarCouple: document.getElementById("topBarCouple"),
  dataSummary: document.getElementById("dataSummary"),
  timelineList: document.getElementById("timelineList"),
  timelineAdminBar: document.getElementById("timelineAdminBar"),
  expenseList: document.getElementById("expenseList"),
  expenseAdminBar: document.getElementById("expenseAdminBar"),
  venueMapContainer: document.getElementById("venueMapContainer"),
  checkinList: document.getElementById("checkinList"),
  checkinSearch: document.getElementById("checkinSearch"),
  galleryGrid: document.getElementById("galleryGrid"),
  galleryAdminBar: document.getElementById("galleryAdminBar"),
};

