export default [
  {
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        fetch: "readonly",
        AbortController: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        requestAnimationFrame: "readonly",
        getComputedStyle: "readonly",
        Map: "readonly",
        Set: "readonly",
        Promise: "readonly",
        URLSearchParams: "readonly",
        URL: "readonly",
        Intl: "readonly",
        performance: "readonly",
        HTMLElement: "readonly",
        KeyboardEvent: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        DOMParser: "readonly",
        location: "readonly",
        requestIdleCallback: "readonly",
        Blob: "readonly",
        alert: "readonly",
        prompt: "readonly",
        history: "readonly",
        Notification: "readonly",
        CSS: "readonly",
        AbortSignal: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        confirm: "readonly",
        FormData: "readonly",
        FileReader: "readonly",
        btoa: "readonly",
        atob: "readonly",
        structuredClone: "readonly",
      },
    },
    rules: {
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-undef": "error",
      "no-dupe-args": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-unused-vars": [
        "warn",
        {
          varsIgnorePattern:
            "^_|^load|^render|^init|^toggle|^update|^handle|^show|^hide|^open|^close|^add|^remove|^save|^delete|^export|^import|^send",
          argsIgnorePattern: "^_|^e$|^k$",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      eqeqeq: ["warn", "smart"],
      "no-var": "warn",
      "no-redeclare": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "prefer-const": "off",
      "no-prototype-builtins": "off",
      "no-inner-declarations": "off",
    },
  },
];
